import os
from dotenv import load_dotenv

load_dotenv()


RECOMMENDATIONS_DB_URL = os.getenv('RECOMMENDATIONS_DB_URL')
RECOMMENDATIONS_DB_USER = os.getenv('RECOMMENDATIONS_DB_USER')
RECOMMENDATIONS_DB_PWD = os.getenv('RECOMMENDATIONS_DB_PWD')
RECOMMENDATIONS_DB = f'postgresql+psycopg2://{RECOMMENDATIONS_DB_USER}:' \
    f'{RECOMMENDATIONS_DB_PWD}@{RECOMMENDATIONS_DB_URL}'
