version: '3'

services:
  api:
    build:
      ./recommendations_api/
    command: "python3 src/main.py"
    depends_on:
      - redis
    restart: on-failure
    ports:
      - 8004:8000
  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379
