version: '3'

volumes:
  data01:
    driver: local

services:
  api:
    build:
      ./recommendations_api/
    command: "python3 src/main.py"
    depends_on:
      - redis
    restart: on-failure
    ports:
      - 8004:8000
  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - 6379:6379

  backend:
    container_name: backend
    build:
      context: api
    ports:
      - 8888:8888
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 29092
      ELASTIC_HOSTS: c-c9qhas1999s0igg1ago7.rw.mdb.yandexcloud.net
    depends_on:
      - redis
      - broker
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/templates/:ro
    environment:
      - API_HOST=http://backend
      - API_PORT=8888
    ports:
      - 0.0.0.0:80:80
    restart: on-failure
