version: '3'

services:
  api:
    build:
      ./api/
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 8004:8000

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=recommendations
      - POSTGRES_USER=${RECOMMENDATIONS_DB_USER}
      - POSTGRES_PASSWORD=${RECOMMENDATIONS_DB_PWD}
    ports:
      - 5432:5432
    volumes:
      - ./recommendations.sql:/docker-entrypoint-initdb.d/init.sql
